### ISSUE TITLE
Laporan Admin Pembelian, Admin Penjualan, dan Admin Gudang tanggal 2 Desember 2020

### ISSUE THREAD

**Issue by Merry01** [AmadeoMB/Export-Import#15]
[Admin Pembelian.docx](https://github.com/AmadeoMB/Export-Import/files/5626763/Admin.Pembelian.docx)
[Admin Penjualan.docx](https://github.com/AmadeoMB/Export-Import/files/5626764/Admin.Penjualan.docx)
[Admin Gudang.docx](https://github.com/AmadeoMB/Export-Import/files/5626767/Admin.Gudang.docx)

**Comment by AmadeoMB** [comment]
Untuk search berdasarkan keyword tidak selalu huruf pertama, pokoknya selama ID dan nama mengandung huruf tersebut yang ada di keyword pasti ditampilkan, tolong diperhatian.
