### ISSUE TITLE
hasil testing admin master dengan pasword staff , dan testing admin Penjualan tgl 7 Desember 2020

### ISSUE THREAD

**Issue by Merry01** [AmadeoMB/Export-Import#18]
[Testing admin master tgl 7 Desember 2021.docx](https://github.com/AmadeoMB/Export-Import/files/5651421/Testing.admin.master.tgl.7.Desember.2021.docx)
[Testing admin Penjualan tgl 7 Desember 2020.docx](https://github.com/AmadeoMB/Export-Import/files/5651423/Testing.admin.Penjualan.tgl.7.Desember.2020.docx)

**Comment by AmadeoMB** [comment]
Fixed
