### ISSUE TITLE
testing admin penjualan dan admin gudang tgl 9 Desember 2020 

### ISSUE THREAD

**Issue by Merry01** [AmadeoMB/Export-Import#19]
[laporan testing admin gudang tgl 8 Desember 2020.docx](https://github.com/AmadeoMB/Export-Import/files/5663610/laporan.testing.admin.gudang.tgl.8.Desember.2020.docx)
[Laporan testing admin penjualan tgl 9 Desember 2020.docx](https://github.com/AmadeoMB/Export-Import/files/5663612/Laporan.testing.admin.penjualan.tgl.9.Desember.2020.docx)

**Comment by AmadeoMB** [comment]
Fixed.
Sebagai catatan, stock akan berubah jika admin membuat PI atai Invoice jadi kalo hanya sekedar SO atau DO atau PO stock tidak akan berubah.
