### ISSUE TITLE
Testing admin gudang, pembelian, dan penjualan tanggal 10 Desember 2020

### ISSUE THREAD

**Issue by MardhanKhrisnabayu26** [AmadeoMB/Export-Import#20]
[Testing Admin Gudang.docx](https://github.com/AmadeoMB/Export-Import/files/5673009/Testing.Admin.Gudang.docx)
[Testing Admin Pembelian.docx](https://github.com/AmadeoMB/Export-Import/files/5673010/Testing.Admin.Pembelian.docx)
[Testing Admin Penjual.docx](https://github.com/AmadeoMB/Export-Import/files/5673011/Testing.Admin.Penjual.docx)

**Comment by AmadeoMB** [comment]
Fixed.
